title: Andru Manuel-Che
description: How I lead and how to work with me
locale: en-AU

remote_theme: "mmistakes/minimal-mistakes@4.28.0"
minimal_mistakes_skin: default

author:
  name: Andru Manuel-Che

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

exclude:
  - NOTES.md
  - CLAUDE.md
  - LICENSE
